USE diskbaseddb
GO

CREATE TABLE ClusteredIndexTable
(ID INT IDENTITY
,UserName VARCHAR(15))

CREATE UNIQUE CLUSTERED INDEX [IX_CLusterIndexTable_ID] ON [dbo].[ClusteredIndexTable]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO